name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^19.5.0
  table_calendar: ^3.0.8
  timezone: ^0.10.1
  android_alarm_manager_plus: ^5.0.0
  fl_chart: ^1.1.1
  image_picker: ^1.2.0
  video_player: ^2.6.0
  chewie: ^1.5.1
  file_picker: ^10.3.3
  url_launcher: ^6.1.11
  syncfusion_flutter_pdfviewer: ^31.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
